name: "Xmpp"
description: "Send xmpp messages"
author: "tong <tong@disktree.net>"
runs:
  using: "node16"
  main: "index.js"
inputs:
  jid:
    description: "Account jabber id (jid)"
    required: true
  password:
    description: "Account password"
    required: true
  message:
    description: "Message to send"
    required: true
  recipient:
    description: "Jid of the message recipient"
    required: false
  muc:
    description: "Muc jid (`room@service/nick`)"
    required: false
  host:
    description: "Server host name"
    required: false
  port:
    description: "Server port"
    required: false
    default: '5222'
