name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        haxe:
        - latest
        - 4.3.1
    steps:
      - uses: actions/checkout@v3
      - name: Install haxe
        uses: krdlab/setup-haxe@v1.5.1
        with:
          haxe-version: ${{ matrix.haxe }}
      - name: Install haxelibs
        run: |
          haxe --version
          haxelib install hxnodejs
          haxelib git sasl https://github.com/tong/hxsasl
          haxelib git hxmpp https://github.com/tong/hxmpp --skip-dependencies
      - name: Build
        run: haxe build.hxml
      - name: Send push event notification
        uses: ./
        if: github.event_name == 'push'
        with:
          jid: ${{ secrets.jid }}
          password: ${{ secrets.password }}
          recipient: ${{ secrets.recipient }}
          message: |
            ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }} with message:
            ${{ join(github.event.commits.*.message) }}
          muc: ${{ secrets.muc }}
      - name: Send pr event notification
        uses: ./
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        with:
          jid: ${{ secrets.jid }}
          password: ${{ secrets.password }}
          recipient: ${{ secrets.recipient }}
          message: |
            ${{ github.actor }} opened a PR : ${{ github.event.pull_request.html_url }} with message :
            ${{ github.event.pull_request.title }}


