name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.2.5
      - name: Setup
        run: |
          haxe --version
          haxelib install hxnodejs
          haxelib git sasl https://github.com/tong/hxsasl
          haxelib git hxmpp https://github.com/tong/hxmpp --skip-dependencies
      - name: Build
        run: haxe build.hxml
      - name: Send push event notification
        uses: ./
        if: github.event_name == 'push'
        with:
          jid: ${{ secrets.jid }}
          password: ${{ secrets.password }}
          recipient: ${{ secrets.recipient }}
          message: |
            ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }} with message:
            ${{ join(github.event.commits.*.message) }}
      - name: Send pr event notification
        uses: ./
        if: github.event_name == 'push'
        with:
          jid: ${{ secrets.jid }}
          password: ${{ secrets.password }}
          recipient: ${{ secrets.recipient }}
          message: |
            ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }} with message:
            ${{ join(github.event.commits.*.message) }}


